import type { Express } from "express";
import type { Server } from "http";
import { api } from "@shared/routes";
import { Resend } from "resend";

const resend = process.env.RESEND_API_KEY ? new Resend(process.env.RESEND_API_KEY) : null;

import { generateSitemap } from "./lib/sitemap";

export async function registerRoutes(
  httpServer: Server,
  app: Express
): Promise<Server> {
  const new_status_date = new Date().toISOString().split('T')[0];
  
  app.post("/api/report-bug", async (req, res) => {
    try {
      if (!resend) {
        console.error("Resend API Key is missing");
        return res.status(500).json({ error: "Email service not configured" });
      }
      // Supporting both old (type, email, message) and new (name, email, subject, message) formats
      const { type, name, email, subject, message } = req.body;
      const reportSubject = subject || type || "General Bug";
      const reporterName = name || "Anonymous User";
      
      const { data, error } = await resend.emails.send({
        from: "AAWhatsApp Support <onboarding@resend.dev>",
        to: ["a67515346@gmail.com"],
        replyTo: email,
        subject: `🚨 Bug Report (V 2.0): ${reportSubject}`,
        html: `
          <!DOCTYPE html>
          <html>
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <style>
                body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #1a1a1a; margin: 0; padding: 0; background-color: #f8fafc; }
                .wrapper { padding: 40px 20px; }
                .container { max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 16px; overflow: hidden; box-shadow: 0 4px 20px rgba(0,0,0,0.05); border: 1px solid #e2e8f0; }
                .header { background: #000000; color: white; padding: 40px 20px; text-align: center; position: relative; }
                .header h1 { margin: 0; font-size: 24px; font-weight: 800; letter-spacing: -0.5px; text-transform: uppercase; }
                .header .brand { color: #22c55e; }
                .content { padding: 40px; }
                .status-badge { display: inline-block; padding: 6px 12px; background: #fee2e2; color: #ef4444; border-radius: 99px; font-size: 12px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 24px; }
                .field { margin-bottom: 32px; }
                .label { font-size: 11px; font-weight: 700; color: #64748b; text-transform: uppercase; letter-spacing: 0.1em; margin-bottom: 8px; display: block; }
                .value { font-size: 16px; color: #0f172a; font-weight: 500; }
                .version-badge { display: inline-block; padding: 4px 10px; background: #f1f5f9; color: #64748b; border: 1px solid #e2e8f0; border-radius: 6px; font-size: 11px; font-weight: 700; }
                .message-box { background: #f1f5f9; padding: 24px; border-radius: 12px; border: 1px solid #e2e8f0; font-family: 'SF Mono', SFMono-Regular, ui-monospace, 'Courier New', monospace; white-space: pre-wrap; font-size: 14px; color: #334155; line-height: 1.7; }
                .footer { background: #f8fafc; padding: 24px; text-align: center; font-size: 12px; color: #94a3b8; border-top: 1px solid #e2e8f0; }
                .footer p { margin: 4px 0; }
              </style>
            </head>
            <body>
              <div class="wrapper">
                <div class="container">
                  <div class="header">
                    <h1>AA<span class="brand">WHATSAPP</span> SUPPORT</h1>
                  </div>
                  <div class="content">
                    <div style="display: flex; justify-content: space-between; align-items: start; margin-bottom: 24px;">
                      <div class="status-badge">Action Required</div>
                      <div class="version-badge">VERSION V 2.0</div>
                    </div>
                    
                    <div class="field">
                      <span class="label">Reporter Name</span>
                      <div class="value">${reporterName}</div>
                    </div>

                    <div class="field">
                      <span class="label">Issue Category/Subject</span>
                      <div class="value" style="font-size: 20px; font-weight: 700;">${reportSubject}</div>
                    </div>

                    <div class="field">
                      <span class="label">Reporter Email</span>
                      <div class="value">${email}</div>
                    </div>

                    <div class="field">
                      <span class="label">Detailed Description</span>
                      <div class="message-box">${message}</div>
                    </div>
                  </div>
                  <div class="footer">
                    <p>Generated by AAWhatsApp Automated Support Intelligence</p>
                    <p>&copy; ${new Date().getFullYear()} AAWhatsApp. Technical Division.</p>
                  </div>
                </div>
              </div>
            </body>
          </html>
        `,
      });

      if (error) {
        console.error("Resend Error:", error);
        return res.status(500).json({ error: "Failed to send email" });
      }

      res.status(200).json({ success: true, data });
    } catch (err) {
      console.error("Server Error:", err);
      res.status(500).json({ error: "Internal server error" });
    }
  });

  app.post(api.subscribers.create.path, async (req, res) => {
    res.status(201).json({ id: 1, email: req.body.email });
  });

  app.post(api.downloads.track.path, async (req, res) => {
    res.status(200).json({ success: true });
  });

  app.get(api.downloads.stats.path, async (req, res) => {
    res.json({ total: 0, android: 0, ios: 0 });
  });

  app.get("/robots.txt", (req, res) => {
    const robots = `User-agent: *
Allow: /
Sitemap: https://aa-mods.vercel.app/sitemap.xml

User-agent: bingbot
Crawl-delay: 1

User-agent: Googlebot
Allow: /`;
    res.type("text/plain");
    res.status(200).send(robots);
  });

  app.get("/88eae1744d0947619ec188fec7ff3b06.txt", (req, res) => {
    res.type("text/plain");
    res.status(200).send("88eae1744d0947619ec188fec7ff3b06");
  });

  app.get("/sitemap.xml", (req, res) => {
    try {
      const sitemap = generateSitemap();
      res.header("Content-Type", "application/xml; charset=utf-8");
      res.status(200).send(sitemap);
    } catch (error) {
      console.error("Sitemap generation error:", error);
      res.status(500).send("Error generating sitemap");
    }
  });

  return httpServer;
}
